### ISSUE TITLE
Can't select image from library

### ISSUE THREAD

**Issue by manufest** [dimitrov-adrian/directus-extension-editorjs-interface#23]
Thanks for your work on this amazing plugin!

I'm having one issue with it. When I insert an image block I can only use the upload or url option from the Directus dialog. When I select from library the drawer opens behind the upload dialog and there is no click-through possible. Trying to select an image closes the dialog overlay and leaves me without an image added.

**Comment by dimitrov-adrian** [comment]
It seems it's Directus issue, as it reproduces also with markdown and wysiwyg editors as well.

**Comment by danieljwestman** [comment]
Any progress with this? It's pretty annoying not being able to choose an existing asset from the library and be forced to upload the same assets over and over again...

I see that Directus core (e.g. in the wysiwyg) solved this with a drawer instead of a dialog:

![Screenshot of Creating Item in Pages](https://user-images.githubusercontent.com/20950568/151669917-ad1f7380-d77e-491f-93c8-8e9a32182f65.jpg)

**Comment by dimitrov-adrian** [comment]
Yea, it's annoying for me too. I had hope core team will take it in their side, as I like modals more than drawers. Anyway, I'll go with the drawer too.

**Comment by dimitrov-adrian** [comment]
Yea, it's annoying for me too. I had hope core team will take it in their side, as I like modals more than drawers. Anyway, I'll go with the drawer too.

**Comment by dimitrov-adrian** [comment]
Fixed after v1.2.1
