### ISSUE TITLE
EditorJs Extension not visible inside Directus 9.5.0

### ISSUE THREAD

**Issue by don41382** [dimitrov-adrian/directus-extension-editorjs-interface#25]
Thanks for the awesome project! But I am not able to get the extension inside of directus working.

I tried to follow your installation steps.

1. Installed extension inside of my fresh Directus repo
```
npm install directus-extension-editorjs
```
2. Run Directus
```
npm run dev
npm run dev -w @directus/app
```
3. Add Field
* Create Field in Advanced Mode
* select Standard Field
* set Schema->Type to JSON
* switch to Interface

In the `Interface` section I can not see EditorJs. What I am missing? And one more question, can I also run your extension from the Directus Docker Image directly?

Thanks for your help!

**Comment by dimitrov-adrian** [comment]
It works with 9.5.0, at least in my environment.

But, I am unsure what this

```
npm run dev
npm run dev -w @directus/app
```

Are you trying to run it with directus from source?

---

The second question about the docker.... There is no official statement about docker and extensions, anyway, I believe the most proper approach if need to go with such type of extensions is to use custom build like

```
# Dockerfile
FROM directus/directus:lateswt
RUN npm install whateverdirectusextension
```

So the control of the bundle will be in your hands.

It could be bit of tricky or anoying to maintain, so in order to tests I recommend goes with using just the dist file and put it in your extensions custom directory as `extensions/interface/editorjs/index.js`

You could get it from here
https://github.com/dimitrov-adrian/directus-extension-editorjs-interface/releases/tag/v1.2.0

**Comment by don41382** [comment]
Thansk Dimitrov for your quick response. And I guess you are right, my development setup for directus is maybe mixed up. I will continue on Monday and let you know.

Thanks for the Docker-Advice. I think thats a good idea. I was hoping for some environment variables to make this possible.

**Comment by dimitrov-adrian** [comment]
Well, for local run it will not works with NPM extensions, because I see you run the app, but actually directus serves all the extension by the backend. So no way to use with cloned repo and dev environment (AFAIK)

About the magic variables... I believe core team are working on it as there is also a draft PR  https://github.com/directus/directus/pull/7891

**Comment by don41382** [comment]
Just to close the issue, I was following the wrong installation guide. After following the [Installation from CLI](https://docs.directus.io/getting-started/installation/cli/) everything works!

Let's hope for the PR to come true. Thanks again for your support Adrian.
